version: '3.4'

services:
  inventario:
    build:
      context: ./
      dockerfile: Inventario/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - db
    ports:
      - '8181:80'

  db: 
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./docker-compose/db/data/db:/data/db:rw
