version: '3.4'

services:
  inventario:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - db
    ports:
      - "8080:8080"

  db: 
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./docker-compose/db/data/db:/data/db:rw